server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true

  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost